step - maps a unit of time in the real world. In this case 1 step is 1 hour of time. Total steps 744 (30 days simulation).

type - CASH-IN, CASH-OUT, DEBIT, PAYMENT and TRANSFER.

amount - amount of the transaction in local currency.

nameOrig - customer who started the transaction

oldbalanceOrg - initial balance before the transaction

newbalanceOrig - new balance after the transaction

nameDest - customer who is the recipient of the transaction

oldbalanceDest - initial balance recipient before the transaction. Note that there is not information for customers that start with M (Merchants).

newbalanceDest - new balance recipient after the transaction. Note that there is not information for customers that start with M (Merchants).

isFraud - This is the transactions made by the fraudulent agents inside the simulation. In this specific dataset the fraudulent behavior of the agents aims to profit by taking control or customers accounts and try to empty the funds by transferring to another account and then cashing out of the system.

isFlaggedFraud - The business model aims to control massive transfers from one account to another and flags illegal attempts. An illegal attempt in this dataset is an attempt to transfer more than 200.000 in a single transaction.

https://www.kaggle.com/arjunjoshua/predicting-fraud-in-financial-payment-services

In [1]:
# import csv
import pandas as pd
#data = pd.read_csv("PS_20174392719_1491204439457_log.csv", nrows=10)
rawdata = pd.read_csv("PS_20174392719_1491204439457_log.csv")
rawdata.head()

# def preprocess(input_file, output_file, keep=1):
#     all_rows = []
#     with open(input_file, 'r') as csvinfile:
#         csv_reader = csv.reader(csvinfile, delimiter=',')
#         for row in csv_reader:
#             all_rows.append(row)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [2]:
df = pd.DataFrame(data=rawdata)

In [3]:
df.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')

In [4]:
df.shape

(6362620, 11)

In [5]:
df_w_dummies=pd.get_dummies(df, columns=['type'])

In [6]:
df_w_dummies_removed = df_w_dummies.drop(['nameOrig', 'nameDest', 'isFlaggedFraud'], axis=1)
df_w_dummies_removed.head()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,type_CASH_IN,type_CASH_OUT,type_DEBIT,type_PAYMENT,type_TRANSFER
0,1,9839.64,170136.0,160296.36,0.0,0.0,0,0,0,0,1,0
1,1,1864.28,21249.0,19384.72,0.0,0.0,0,0,0,0,1,0
2,1,181.00,181.0,0.00,0.0,0.0,1,0,0,0,0,1
3,1,181.00,181.0,0.00,21182.0,0.0,1,0,1,0,0,0
4,1,11668.14,41554.0,29885.86,0.0,0.0,0,0,0,0,1,0

In [7]:
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler(feature_range=(0, 1), copy=True)
scaled_df = scaler.fit_transform(df_w_dummies_removed)
# scaled_df_1 = pd.DataFrame(scaled_df, columns=['amount','oldbalanceOrg','newbalanceOrig','oldbalanceDest','newbalanceDest'], copy=True)
scaled_df_1 = pd.DataFrame(scaled_df)
# # scaled_df = preprocessing.MinMaxScaler(feature_range=(0, 1), copy=True)
scaled_df_1.head()

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:334: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.0,0.000106,0.002855,0.003233,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.000020,0.000357,0.000391,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.000002,0.000003,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.000002,0.000003,0.000000,0.000059,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.000126,0.000697,0.000603,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [8]:
cols = scaled_df_1.columns.tolist()
cols = cols[-1:] + cols[:-1]
cols
scaled_df_1 = scaled_df_1[cols]
scaled_df_1

,11,0,1,2,3,4,5,6,7,8,9,10
0,0.0,0.000000,0.000106,0.002855,0.003233,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
1,0.0,0.000000,0.000020,0.000357,0.000391,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
2,1.0,0.000000,0.000002,0.000003,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
3,0.0,0.000000,0.000002,0.000003,0.000000,0.000059,0.000000,1.0,0.0,1.0,0.0,0.0
4,0.0,0.000000,0.000126,0.000697,0.000603,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
5,0.0,0.000000,0.000085,0.000904,0.000929,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
6,0.0,0.000000,0.000077,0.003075,0.003551,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
7,0.0,0.000000,0.000085,0.002955,0.003393,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
8,0.0,0.000000,0.000044,0.000045,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
9,0.0,0.000000,0.000058,0.000700,0.000734,0.000118,0.000113,0.0,0.0,0.0,1.0,0.0
10,0.0,0.000000,0.000104,0.000075,0.000000,0.000030,0.000444,0.0,0.0,0.0,1.0,0.0
11,0.0,0.000000,0.000034,0.000349,0.000356,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
12,0.0,0.000000,0.000028,0.000085,0.000051,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
13,0.0,0.000000,0.000126,0.000170,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
14,0.0,0.000000,0.000044,0.008446,0.010067,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
15,0.0,0.000000,0.002479,0.000257,0.000000,0.000014,0.000145,0.0,0.0,1.0,0.0,0.0
16,0.0,0.000000,0.000017,0.000008,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
17,0.0,0.000000,0.000013,0.000355,0.000403,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
18,0.0,0.000000,0.000007,0.000254,0.000291,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
19,1.0,0.000000,0.002329,0.000012,0.000000,0.000063,0.000000,0.0,0.0,0.0,0.0,0.0
20,0.0,0.000000,0.000015,0.000233,0.000252,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
21,0.0,0.000000,0.000101,0.000190,0.000040,0.000084,0.000047,0.0,0.0,0.0,1.0,0.0
22,0.0,0.000000,0.000012,0.000030,0.000015,0.000029,0.000000,0.0,0.0,0.0,1.0,0.0
23,0.0,0.000000,0.000042,0.001139,0.001290,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
24,1.0,0.000000,0.003372,0.000182,0.000000,0.000018,0.007634,0.0,0.0,0.0,0.0,0.0
25,0.0,0.000000,0.000066,0.000007,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
26,0.0,0.000000,0.000103,0.001955,0.002158,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
27,0.0,0.000000,0.000087,0.000184,0.000060,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
28,0.0,0.000000,0.000096,0.000050,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
29,0.0,0.000000,0.000107,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6362590,1.0,0.997305,0.003502,0.005433,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362591,0.0,0.997305,0.003502,0.005433,0.000000,0.001578,0.002486,1.0,0.0,1.0,0.0,0.0
6362592,1.0,0.997305,0.004150,0.006439,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362593,0.0,0.997305,0.004150,0.006439,0.000000,0.005023,0.006097,1.0,0.0,1.0,0.0,0.0
6362594,1.0,0.997305,0.001568,0.002433,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362595,0.0,0.997305,0.001568,0.002433,0.000000,0.000000,0.000407,1.0,0.0,1.0,0.0,0.0
6362596,1.0,0.997305,0.000524,0.000813,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362597,0.0,0.997305,0.000524,0.000813,0.000000,0.001443,0.001578,1.0,0.0,1.0,0.0,0.0
6362598,1.0,0.998652,0.043367,0.067283,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362599,0.0,0.998652,0.043367,0.067283,0.000000,0.003454,0.014708,1.0,0.0,1.0,0.0,0.0
6362600,1.0,0.998652,0.007064,0.010959,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362601,0.0,0.998652,0.007064,0.010959,0.000000,0.000000,0.001833,1.0,0.0,1.0,0.0,0.0
6362602,1.0,0.998652,0.019682,0.030537,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362603,0.0,0.998652,0.019682,0.030537,0.000000,0.000000,0.005109,1.0,0.0,1.0,0.0,0.0
6362604,1.0,0.998652,0.000591,0.000917,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362605,0.0,0.998652,0.000591,0.000917,0.000000,0.000000,0.000153,1.0,0.0,1.0,0.0,0.0
6362606,1.0,0.998652,0.003287,0.005099,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362607,0.0,0.998652,0.003287,0.005099,0.000000,0.000965,0.001818,1.0,0.0,1.0,0.0,0.0
6362608,1.0,0.998652,0.002795,0.004336,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362609,0.0,0.998652,0.002795,0.004336,0.000000,0.000071,0.000796,1.0,0.0,1.0,0.0,0.0
6362610,1.0,0.998652,0.000686,0.001064,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362611,0.0,0.998652,0.000686,0.001064,0.000000,0.000776,0.000954,1.0,0.0,1.0,0.0,0.0
6362612,1.0,1.000000,0.013617,0.021126,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362613,0.0,1.000000,0.013617,0.021126,0.000000,0.001414,0.004948,1.0,0.0,1.0,0.0,0.0
6362614,1.0,1.000000,0.003674,0.005701,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362615,0.0,1.000000,0.003674,0.005701,0.000000,0.000000,0.000954,1.0,0.0,1.0,0.0,0.0
6362616,1.0,1.000000,0.068272,0.105923,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362617,0.0,1.000000,0.068272,0.105923,0.000000,0.000192,0.017912,1.0,0.0,1.0,0.0,0.0
6362618,1.0,1.000000,0.009195,0.014265,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
6362619,0.0,1.000000,0.009195,0.014265,0.000000,0.018286,0.020664,1.0,0.0,1.0,0.0,0.0

In [10]:
#Splitting data into train and validation
import numpy as np
train_data, validation_data, test_data = np.split(scaled_df_1.sample(frac=1, random_state=1729), [int(0.7 * len(scaled_df_1)), int(0.9 * len(scaled_df_1))])
train_data.to_csv('train.csv', header=False, index=False)
validation_data.to_csv('validation.csv', header=False, index=False)

START THE MODEL STEP

In [11]:
final_df= scaled_df_1
final_df.head()
Y = final_df[6]
Y.head()
X = final_df.drop([6], axis=1)
X.head()

    11   0         1         2         3         4    5    7    8    9    10
0  0.0  0.0  0.000106  0.002855  0.003233  0.000000  0.0  0.0  0.0  0.0  1.0
1  0.0  0.0  0.000020  0.000357  0.000391  0.000000  0.0  0.0  0.0  0.0  1.0
2  1.0  0.0  0.000002  0.000003  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.000002  0.000003  0.000000  0.000059  0.0  0.0  1.0  0.0  0.0
4  0.0  0.0  0.000126  0.000697  0.000603  0.000000  0.0  0.0  0.0  0.0  1.0

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1)
# train_set, validation_set = train_test_split(train_set, test_size=0.1, random_state=1)

Collecting xgboost
  Downloading https://files.pythonhosted.org/packages/c1/24/5fe7237b2eca13ee0cfb100bec8c23f4e69ce9df852a64b0493d49dae4e0/xgboost-0.90-py2.py3-none-manylinux1_x86_64.whl (142.8MB)
    100% |████████████████████████████████| 142.8MB 362kB/s eta 0:00:011    89% |████████████████████████████▌   | 127.1MB 89.2MB/s eta 0:00:01
Requirement already satisfied: numpy in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from xgboost) (1.15.4)
Requirement already satisfied: scipy in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from xgboost) (1.1.0)
Installing collected packages: xgboost
Successfully installed xgboost-0.90
You are using pip version 10.0.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [21]:
import xgboost as xgb
gbm = xgb.XGBClassifier(max_depth=5, n_estimators=150, learning_rate=0.05).fit(X_train, Y_train)

[15:30:12] WARNING: /workspace/src/learner.cc:686: Tree method is automatically selected to be 'approx' for faster speed. To use old behavior (exact greedy algorithm on single machine), set tree_method to 'exact'.

KeyboardInterrupt:

In [ ]:
predictions = gbm.predict(X_test)

In [ ]:


pd.crosstab(np.round(Y_test), columns = np.where(predictions>0.3, 1, 0), rownames=['actual'], colnames=['predictions'])